// lib/countries.ts
// Comprehensive list of all countries in the world

export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Scotland",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Wales",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

// Country name to ISO 3166-1 alpha-2 code mapping for flag emojis
export function countryToFlag(country?: string | null): string | null {
  if (!country) return null;
  
  const code = getCountryCode(country);
  if (!code) return null;

  // Convert ISO country code to flag emoji
  const codePoints = Array.from(code).map((char) => {
    const base = 0x1f1e6; // Regional Indicator Symbol Letter A
    return base + (char.toUpperCase().charCodeAt(0) - 65);
  });

  return String.fromCodePoint(...codePoints);
}

// Helper function to get country code from country name (shared between functions)
function getCountryCode(country: string): string | null {
  const trimmed = country.trim();
  const key = trimmed.toLowerCase();

  const nameToCode: Record<string, string> = {
    // Common variations
    "united kingdom": "GB",
    uk: "GB",
    "u.k.": "GB",
    england: "GB",
    scotland: "GB",
    wales: "GB",
    "united states": "US",
    usa: "US",
    "u.s.a.": "US",
    america: "US",
    "united states of america": "US",
    
    // All countries
    afghanistan: "AF",
    albania: "AL",
    algeria: "DZ",
    andorra: "AD",
    angola: "AO",
    "antigua and barbuda": "AG",
    argentina: "AR",
    armenia: "AM",
    australia: "AU",
    austria: "AT",
    azerbaijan: "AZ",
    bahamas: "BS",
    bahrain: "BH",
    bangladesh: "BD",
    barbados: "BB",
    belarus: "BY",
    belgium: "BE",
    belize: "BZ",
    benin: "BJ",
    bhutan: "BT",
    bolivia: "BO",
    "bosnia and herzegovina": "BA",
    botswana: "BW",
    brazil: "BR",
    brunei: "BN",
    bulgaria: "BG",
    "burkina faso": "BF",
    burundi: "BI",
    "cabo verde": "CV",
    cambodia: "KH",
    cameroon: "CM",
    canada: "CA",
    "central african republic": "CF",
    chad: "TD",
    chile: "CL",
    china: "CN",
    colombia: "CO",
    comoros: "KM",
    congo: "CG",
    "costa rica": "CR",
    croatia: "HR",
    cuba: "CU",
    cyprus: "CY",
    "czech republic": "CZ",
    denmark: "DK",
    djibouti: "DJ",
    dominica: "DM",
    "dominican republic": "DO",
    ecuador: "EC",
    egypt: "EG",
    "el salvador": "SV",
    "equatorial guinea": "GQ",
    eritrea: "ER",
    estonia: "EE",
    eswatini: "SZ",
    ethiopia: "ET",
    fiji: "FJ",
    finland: "FI",
    france: "FR",
    gabon: "GA",
    gambia: "GM",
    georgia: "GE",
    germany: "DE",
    ghana: "GH",
    greece: "GR",
    grenada: "GD",
    guatemala: "GT",
    guinea: "GN",
    "guinea-bissau": "GW",
    guyana: "GY",
    haiti: "HT",
    honduras: "HN",
    hungary: "HU",
    iceland: "IS",
    india: "IN",
    indonesia: "ID",
    iran: "IR",
    iraq: "IQ",
    ireland: "IE",
    "republic of ireland": "IE",
    israel: "IL",
    italy: "IT",
    jamaica: "JM",
    japan: "JP",
    jordan: "JO",
    kazakhstan: "KZ",
    kenya: "KE",
    kiribati: "KI",
    kosovo: "XK",
    kuwait: "KW",
    kyrgyzstan: "KG",
    laos: "LA",
    latvia: "LV",
    lebanon: "LB",
    lesotho: "LS",
    liberia: "LR",
    libya: "LY",
    liechtenstein: "LI",
    lithuania: "LT",
    luxembourg: "LU",
    madagascar: "MG",
    malawi: "MW",
    malaysia: "MY",
    maldives: "MV",
    mali: "ML",
    malta: "MT",
    "marshall islands": "MH",
    mauritania: "MR",
    mauritius: "MU",
    mexico: "MX",
    micronesia: "FM",
    moldova: "MD",
    monaco: "MC",
    mongolia: "MN",
    montenegro: "ME",
    morocco: "MA",
    mozambique: "MZ",
    myanmar: "MM",
    namibia: "NA",
    nauru: "NR",
    nepal: "NP",
    netherlands: "NL",
    "new zealand": "NZ",
    nicaragua: "NI",
    niger: "NE",
    nigeria: "NG",
    "north korea": "KP",
    "north macedonia": "MK",
    norway: "NO",
    oman: "OM",
    pakistan: "PK",
    palau: "PW",
    palestine: "PS",
    panama: "PA",
    "papua new guinea": "PG",
    paraguay: "PY",
    peru: "PE",
    philippines: "PH",
    poland: "PL",
    portugal: "PT",
    qatar: "QA",
    romania: "RO",
    russia: "RU",
    rwanda: "RW",
    "saint kitts and nevis": "KN",
    "saint lucia": "LC",
    "saint vincent and the grenadines": "VC",
    samoa: "WS",
    "san marino": "SM",
    "sao tome and principe": "ST",
    "saudi arabia": "SA",
    senegal: "SN",
    serbia: "RS",
    seychelles: "SC",
    "sierra leone": "SL",
    singapore: "SG",
    slovakia: "SK",
    slovenia: "SI",
    "solomon islands": "SB",
    somalia: "SO",
    "south africa": "ZA",
    "south korea": "KR",
    "south sudan": "SS",
    spain: "ES",
    "sri lanka": "LK",
    sudan: "SD",
    suriname: "SR",
    sweden: "SE",
    switzerland: "CH",
    syria: "SY",
    taiwan: "TW",
    tajikistan: "TJ",
    tanzania: "TZ",
    thailand: "TH",
    "timor-leste": "TL",
    togo: "TG",
    tonga: "TO",
    "trinidad and tobago": "TT",
    tunisia: "TN",
    turkey: "TR",
    turkmenistan: "TM",
    tuvalu: "TV",
    uganda: "UG",
    ukraine: "UA",
    "united arab emirates": "AE",
    uzbekistan: "UZ",
    vanuatu: "VU",
    "vatican city": "VA",
    venezuela: "VE",
    vietnam: "VN",
    yemen: "YE",
    zambia: "ZM",
    zimbabwe: "ZW",
  };

  // If it's already a 2-letter code, use it directly
  if (/^[a-z]{2}$/i.test(trimmed)) {
    return trimmed.toUpperCase();
  } else if (nameToCode[key]) {
    return nameToCode[key];
  }

  return null;
}

// Get flag image URL from CDN (better browser compatibility than emojis)
export function countryToFlagUrl(country?: string | null): string | null {
  if (!country) return null;
  
  const code = getCountryCode(country);
  if (!code) return null;

  // Use flagcdn.com for flag images (free, no API key required, reliable CDN)
  return `https://flagcdn.com/w20/${code.toLowerCase()}.png`;
}

