export const ALL_LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Español (Spanish)' },
  { code: 'fr', label: 'Français (French)' },
  { code: 'de', label: 'Deutsch (German)' },
  { code: 'pt', label: 'Português (Portuguese)' },
  { code: 'it', label: 'Italiano (Italian)' },
  { code: 'nl', label: 'Nederlands (Dutch)' },
  { code: 'pl', label: 'Polski (Polish)' },
  { code: 'ru', label: 'Русский (Russian)' },
  { code: 'ja', label: '日本語 (Japanese)' },
  { code: 'ko', label: '한국어 (Korean)' },
  { code: 'zh-CN', label: '简体中文 (Chinese Simplified)' },
  { code: 'ar', label: 'العربية (Arabic)' },
  { code: 'tr', label: 'Türkçe (Turkish)' },
  { code: 'hi', label: 'हिन्दी (Hindi)' },
  { code: 'bn', label: 'বাংলা (Bengali)' },
  { code: 'vi', label: 'Tiếng Việt (Vietnamese)' },
  { code: 'th', label: 'ไทย (Thai)' },
  { code: 'id', label: 'Bahasa Indonesia (Indonesian)' },
  { code: 'ms', label: 'Bahasa Melayu (Malay)' },
  { code: 'fil', label: 'Filipino' },
  { code: 'iw', label: 'עברית (Hebrew)' },
  { code: 'fa', label: 'فارسی (Persian)' },
  { code: 'sv', label: 'Svenska (Swedish)' },
  { code: 'no', label: 'Norsk (Norwegian)' },
  { code: 'da', label: 'Dansk (Danish)' },
  { code: 'fi', label: 'Suomi (Finnish)' },
  { code: 'el', label: 'Ελληνικά (Greek)' },
  { code: 'hu', label: 'Magyar (Hungarian)' },
  { code: 'cs', label: 'Čeština (Czech)' },
  { code: 'ro', label: 'Română (Romanian)' },
  { code: 'uk', label: 'Українська (Ukrainian)' },
  { code: 'ig', label: 'Igbo' },
  { code: 'yo', label: 'Yoruba' },
  { code: 'zu', label: 'Zulu' },
  { code: 'sw', label: 'Swahili' },
  { code: 'af', label: 'Afrikaans' },
  { code: 'sq', label: 'Shqip (Albanian)' },
  { code: 'hy', label: 'Հայերեն (Armenian)' },
  { code: 'az', label: 'Azərbaycan (Azerbaijani)' },
  { code: 'eu', label: 'Euskara (Basque)' },
  { code: 'be', label: 'Беларуская (Belarusian)' },
  { code: 'bs', label: 'Bosanski (Bosnian)' },
  { code: 'bg', label: 'Български (Bulgarian)' },
  { code: 'ca', label: 'Català (Catalan)' },
  { code: 'hr', label: 'Hrvatski (Croatian)' },
  { code: 'et', label: 'Eesti (Estonian)' },
  { code: 'gl', label: 'Galego (Galician)' },
  { code: 'ka', label: 'ქართული (Georgian)' },
  { code: 'gu', label: 'ગુજરાતી (Gujarati)' },
  { code: 'ht', label: 'Kreyòl Ayisyen (Haitian Creole)' },
  { code: 'ha', label: 'Hausa' },
  { code: 'is', label: 'Íslenska (Icelandic)' },
  { code: 'jw', label: 'Basa Jawa (Javanese)' },
  { code: 'kn', label: 'ಕನ್ನಡ (Kannada)' },
  { code: 'kk', label: 'Қазақ (Kazakh)' },
  { code: 'km', label: 'ខ្មែរ (Khmer)' },
  { code: 'ky', label: 'Кыргызча (Kyrgyz)' },
  { code: 'lo', label: 'ລາວ (Lao)' },
  { code: 'la', label: 'Latina (Latin)' },
  { code: 'lv', label: 'Latviešu (Latvian)' },
  { code: 'lt', label: 'Lietuvių (Lithuanian)' },
  { code: 'lb', label: 'Lëtzebuergesch (Luxembourgish)' },
  { code: 'mk', label: 'Македонски (Macedonian)' },
  { code: 'mg', label: 'Malagasy' },
  { code: 'mt', label: 'Malti (Maltese)' },
  { code: 'mi', label: 'Maori' },
  { code: 'mr', label: 'मराठी (Marathi)' },
  { code: 'mn', label: 'Монгол (Mongolian)' },
  { code: 'my', label: 'မြန်မာ (Burmese)' },
  { code: 'ne', label: 'नेपाली (Nepali)' },
  { code: 'ps', label: 'پښتو (Pashto)' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ (Punjabi)' },
  { code: 'sm', label: 'Samoan' },
  { code: 'gd', label: 'Gàidhlig (Scots Gaelic)' },
  { code: 'sr', label: 'Српски (Serbian)' },
  { code: 'st', label: 'Sesotho' },
  { code: 'sn', label: 'Shona' },
  { code: 'sd', label: 'سنڌي (Sindhi)' },
  { code: 'si', label: 'සිංහල (Sinhala)' },
  { code: 'sk', label: 'Slovenčina (Slovak)' },
  { code: 'sl', label: 'Slovenščina (Slovenian)' },
  { code: 'so', label: 'Somali' },
  { code: 'su', label: 'Basa Sunda (Sundanese)' },
  { code: 'tg', label: 'Тоҷикӣ (Tajik)' },
  { code: 'ta', label: 'தமிழ் (Tamil)' },
  { code: 'te', label: 'తెలుగు (Telugu)' },
  { code: 'ur', label: 'اردو (Urdu)' },
  { code: 'uz', label: 'Oʻzbek (Uzbek)' },
  { code: 'cy', label: 'Cymraeg (Welsh)' },
  { code: 'xh', label: 'IsiXhosa' },
  { code: 'yi', label: 'ייִדיש (Yiddish)' }
];
